export const ActivityType = {
  APPLICATION_CREATED: "APPLICATION_CREATED",
  STAGE_CHANGED: "STAGE_CHANGED",
  RECRUITER_ASSIGNED: "RECRUITER_ASSIGNED",
  NOTE_ADDED: "NOTE_ADDED",
  INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",
  STATUS_CHANGED: "STATUS_CHANGED",
  ATTACHMENT_ADDED: "ATTACHMENT_ADDED",
  EMAIL_SENT: "EMAIL_SENT",
} as const;

export type ActivityType = (typeof ActivityType)[keyof typeof ActivityType];
